### PR TITLE
Create config-CentOS-Stream-Linux-9.0-ALL

### PR DESCRIPTION
**Pull request by jamesdev01**

### CODE REVIEW

**Comment by iliajie** [comment]
Hello,

We don't need this config as we already have `config-CentOS-Stream-Linux-8.0-ALL` that covers that all.

**Comment by jamesdev01** [comment]
CenOS Stream is a separate operating system.

**Comment by jamesdev01** [comment]
This is for version 9.0, but yours is for version 8.0

**Comment by iliajie** [comment]
> I see, the naming of it was confusing, made me think that it only covered the version that was listed. After looking further at the source code, I understand now.

Yes, `8.0-ALL` covers all .. 8 and up.

**Pull request closed without merging**
