### PR TITLE
Merge newly created README.md

### PR DESCRIPTION
**Pull request by jamesdev01**
I built a readme page including detailed instructions and description for how to install this plugin. Included badges and full details. Once committed, it will display on the main page as the decription to help users install this. 

Edit: Updated my former commit by creating and adding broken badges and fixing description.

### CODE REVIEW

**Comment by jamesdev01** [comment]
There is a lot more incuded than just installing nginx, as it is involved. Quite a bit of packages and things. I can remove it, but then people will just have to google all over the place to do it.

**Comment by jamesdev01** [comment]
Also I hope you didn't mean remove my instructions in the install section on where to navigate, because that was actually the entire purpose of making the readme.

**Comment by swelljoe** [comment]
> It would be really unfortunate to have any of this information missing from the installer, becaues then people won't be able to install it without googling lots of random places and possibly breaking their install if they follow the wrong instructions.

These _are_ the wrong instructions, though!

The right instructions are:

1. Download the virtualmin-install.sh install script.
2. Run `/bin/sh virtualmin-install.sh -b LEMP`

**Comment by jamesdev01** [comment]
Are you suggesting that nginx and php are automatically installed? Because I had to do all this manually. There are no instructions on your website, and it was not ubilt into the installer, I had to do it myself, as would anyone who wants to use this plugin.

Then after everything was installed, I had to learn how to get your plugin installed, because there were no instructions, not even any documentation on what this was and how to use it.

That's why I created this README file so that people could know what it is and how to install it all in one place, without having to go off onto random websites that might give the wrong information.

This is what I consider fundamental to a functioning webserver. I don't think that anyone should be running a web server without nginx and a reverse proxy. I'm glad you created it, but I only found it by accident and only later discovered that it was not a 3rd party plugin (because there are also lots of 3rd party plugins).

The lack of documentation was challenging. I really think this should be a default package in Webmin or virtualmin, it is as fundamental as apache. I was looking for something similar to Engintron for cPanel, which is an NGINX with reverse proxy that requires zero configuration and one-line install and removal.

Please give me feedback about this.

**Comment by swelljoe** [comment]
> Are you suggesting that nginx and php are automatically installed? 

I'm not merely suggesting it, I am saying it plainly. The install script installs everything needed for a fully functional hosting system. If you choose the `-b LEMP` option, the web server in that hosting system will be `nginx`.

**Comment by jamesdev01** [comment]
> 2\. Run `/bin/sh virtualmin-install.sh -b LEMP`

There is a difference between "my instructions are wrong" and "we have a simpler script that does the same as your correct instructions". I did not know about that, as I previously stated there is no documentation anywhere which is why I made this README file.

**Comment by swelljoe** [comment]
But, there _is_ documentation. How did you find Virtualmin without finding Virtualmin.com where the documentation lives?

**Comment by jamesdev01** [comment]
> https://www.virtualmin.com/documentation/installation/automated/#LAMP_vs_LEMP

This page is not very clear and there is no indication whatsoever it has anything to do with this plugin. Maybe I can help clean up the UI/UX issues.

**Comment by jamesdev01** [comment]
> But, there _is_ documentation. How did you find Virtualmin without finding Virtualmin.com where the documentation lives?


Maybe you are confused. The whole point of all this is a plugin. Nothing I am doing or discussing here is about the install of the core control panel, Virtualmin. I'm only discussing this NGINX plugin.

**Comment by jamesdev01** [comment]
> Sorry I'm being kind of an ass. I appreciate your efforts. I'm just frustrated. We're talking past one another.
> 
> > I'm only discussing this NGINX plugin.
> 
> The nginx plugin is only usable on a system that is setup for it. The `-b LEMP` option to the installer sets up the system for use with this plugin, and installs this plugin (and the nginx-ssl plugin, too).
> 
> We do not support configurations that include both Apache and nginx. You either choose an Apache installation or Virtualmin or an nginx installation of Virtualmin. You should do that _at installation time_. You can't reasonably install the Apache version and then add the nginx plugin; it won't work. You can't switch from Apache to nginx without a backup/restore.

You clearly have no thoughts about the user, and make a lot of assumptions, many which are false.

"You can't reasonably install the Apache version and then add the nginx plugin; it won't work." Absolutely and categorically false. It's called a reverse proxy. Engintron for cPanelw uses both Apache and NIGINX and has the benefits of both.

But what this exactly is, is exactly why a README file describing what this plugin is and what it does is so important. How was I supposed to know that? I'm about to give up on this control panel for good and just suck it up and go back to cPanel.

I feel like I just wasted my time. And why would you want a LESS formatted README file? Like you hate centering? No need to be a luddite, it's time to leave 1999 behind. 

"It's not needed" was your statement, I can see you don't place any value on aesthetics and usability. That attitude must be the reason why Webmin and Virtualmin have such an outdated interface, it's clear that UI and UX play very little role in the development of this software. 

The lack of even a README file or installation instructions, and the criticism of anyone who is willing to spend their own time to help,  Failure to be able to take feedback and improve is why the interface has remained virtually unchanged with icons that are 20 years old from the dotcom boom. I have followed your project over the years,

**Comment by jamesdev01** [comment]
And if there is something about the way you built Virtualmin that **prevents** the ability for Apache and NGINX to work together, than I have no use for your entire web panel. I will find one that is nore updated, a lot has happened in the web world since 1999.

**Comment by swelljoe** [comment]
> And if there is something about the way you built Virtualmin that prevents the ability for Apache and NGINX to work together, than I have no use for your entire web panel.

No, but this plugin doesn't do that. And, I wouldn't recommend you do that. It is a waste of resources. If you like nginx, use nginx (we support that). If you like Apache, use Apache (we support that, too). If you want nginx _and_ Apache, I believe you're making a mistake, and we're not going to provide UI and installer support for a configuration we think is a mistake.

**Comment by jamesdev01** [comment]
> > And if there is something about the way you built Virtualmin that prevents the ability for Apache and NGINX to work together, than I have no use for your entire web panel.
> 
> No, but this plugin doesn't do that. And, I wouldn't recommend you do that. It is a waste of resources. If you like nginx, use nginx (we support that). If you like Apache, use Apache (we support that, too). If you want nginx _and_ Apache, I believe you're making a mistake, and we're not going to provide UI and installer support for a configuration we think is a mistake.

Yes, I can see that you have no idea to provide an experience either UI or UX that is dated anywhere newer than before the dotcom boom.

Your unprofesionalness, and stubborn refusal to take people's advice that someone might know something better than you, and your cursing and criticism of people trying to help, make me understand why so many other better control panels have been able to pop up. 

ou were positioned to be able to domainate the market and like CentOS, be the foundation FOSS to put companies like cPanel out of business. But because of your stubborn refusal to listen and know-it-all attitude that is very outdated, refusal to come into the 21st century, I can understand why so few people use this software despite it being free.

**Comment by swelljoe** [comment]
Look, I'm sorry we got off on the wrong foot on this. As I said, I appreciate your efforts. But, I think what you want this plugin to be is different from what it actually is. I see we do need to improve the documentation to make it more clear how to get an nginx installation.

And, we should have a README on all of our plugins here, since folks will stumble on them from time to time, and it should be clear what they do.

**Comment by jamesdev01** [comment]
> Look, I'm sorry we got off on the wrong foot on this. As I said, I appreciate your efforts. But, I think what you want this plugin to be is different from what it actually is. I see we do need to improve the documentation to make it more clear how to get an nginx installation.
> 
> And, we should have a README on all of our plugins here, since folks will stumble on them from time to time, and it should be clear what they do.

You absolutely should have adequate or at least minimal documentation like README pages. That's what I've been trying to tell you. I wanted to contribute and help but your continual crushing what I'm advising and helping you with is not making me very enthusastic about helping with this project.

I think you need to consider some self-reflection. If you want to have people pay $20 per month to use Virtualmin, few people are going to do that if you don't update the interface and support the latest technologies. There are currently other much better control panels for a similar cost.

$20 per month is not free. And I can see that Virtualmin does not allow reseller accounts without payment, which completely defeats the purpose of using webmin/virtualmin.

I will go now, hope you can get your act together, learn to be professional, and drop the know-it-all attitude and chasing away new contributors willing to spend hours of their time to help you for free. You're not even FOSS.

**Comment by swelljoe** [comment]
Best of luck with whatever control panel you choose.

**Comment by jamesdev01** [comment]
> Best of luck with whatever control panel you choose.

Probably go back to cPanel. At least I can get a working Apache_NGINX reverse proxy and the software works, so even though the support is just as bad, at least there is no need for the support, unlike this software. And the interface there is at least modern and usable, and the documentation is excellent.

I guess you have to pay if you want something good. I thought I might be able to even use my skills to help yours surpass cPanel, but you don' want to listen.

Best of luck with your company. Can't say I didn't try.

**Comment by jamesdev01** [comment]
I'm deleting my whole repository. Sorry you didn't want any help.

**Comment by jamesdev01** [comment]
Everyhting you wrote was incorrect. This unprofessional thickheaded luddite attitude will be your undoing.

**Pull request closed without merging**
